# 仓库地址，填写 Fork 后的仓库地址，支持 Gitee / GitHub / GitLab
gitRepoUrl: https://github.com/goldsame/necessarytool1.0

# Fork 部署分支
branch: main

# 默认Fork仓库
imageRepoUrl: ''

# 只有GitHub pages用户需要设置为true，其他建议设置为false
hashMode: true

# 一旦填写认为你是自有部署，Fork 不要填写
address: ''

# 自有部署后台登录密码
password: admin

# 自有部署启动端口
port: 7777

# 收录通知邮箱
email: ''

# 自有部署邮件通知系统
mailConfig:
  host: smtp.mxhichina.com
  port: 465
  secure: true
  auth:
    user: ''
    pass: ''
  title: 网站收录通知
  message: 有用户提交网站收录啦

# 自有部署
XFAPIPassword: ''
